title: 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: "tonybloc.github.io"
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://tonybloc.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tonybloc

# Build settings
# theme: bulma-clean-theme
# With GitHub Pages Gem
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-feed